config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get "log_in" => "sessions#new", :as => "log_in"  
  get "log_out" => "sessions#destroy", :as => "log_out"  
  
  get "sign_up" => "users#new", :as => "sign_up" 
  resources :users  
  resources :sessions  

  resources :chat

  root 'chat#index'

end

app/models/chatlog.rb
class Chatlog < ActiveRecord::Base
	belongs_to :user
end

app/models/roomstate.rb
class Roomstate < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :chatlogs
	
	attr_accessor :password  
	before_save :encrypt_password  

	validates_confirmation_of :password  
	validates_presence_of :password, :on => :create  
	validates_presence_of :email  
	validates_uniqueness_of :email  

	def encrypt_password  
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt  
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)  
		end  
	end

	def self.authenticate(email, password)  
		user = find_by_email(email)  
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)  
		  user  
		else  
		  nil  
		end  
	end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	helper_method :current_user  
    
  private  
  def current_user  
    @current_user ||= User.find(session[:user_id]) if session[:user_id]  
  end  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index
    @paintroom = [1, 2, 3, 4]
  end

  def show
    @webchannel = "websocket_chat_channel_" + params[:id].to_s
    @webpaintchannel = "websocket_paint_channel_" + params[:id].to_s
    @webuserchannel = "websocket_user_channel_" + params[:id].to_s
    @webmychannel = "web_my_channel_" + params[:id].to_s + "_" + current_user.id.to_s
    session[:room_id] = params[:id].to_s

    if Chatlog.where("room_num = ?", session[:room_id]).count > 17
      cnt = Chatlog.where("room_num = ?", session[:room_id]).count - 18
    else
      cnt = 0
    end
    @chatlogs = Chatlog.where("room_num = ?", session[:room_id]).all.order(id: :asc).limit(18).offset(cnt)
    p @webmychannel
  end

  def pain
  	if Chatlog.count > 17
  		cnt = Chatlog.count - 18
  	else
  		cnt = 0
  	end
  	@chatlogs = Chatlog.all.order(id: :asc).limit(18).offset(cnt)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new  
  end  
    
  def create  
    user = User.authenticate(params[:email], params[:password])  
    if user  
      session[:user_id] = user.id  
      redirect_to root_url, :notice => "Logged in!"  
    else  
      flash.now.alert = "Invalid email or password"  
      render "new"  
    end  
  end

	def destroy  
	  session[:user_id] = nil  
	  redirect_to root_url, :notice => "Logged out!"  
	end  
end

app/controllers/tailchats_controller.rb
class TailchatsController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new  
    @user = User.new  
  end  
  def show
    
  end

  def edit
    @user = User.find_by(id: current_user.id)
  end

  def update
    @user = User.find params[:id]
    if @user.update(user_params)
      redirect_to root_url, :notice => "edit up!"
    else
      render "edit"
    end
  end

  def create 
    @user = User.new(user_params)  
    if @user.save  
      redirect_to root_url, :notice => "Signed up!"  
    else  
      render "new" 
    end
  end  

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username)
  end
end

app/controllers/websocket_chat_controller.rb
class WebsocketChatController < WebsocketRails::BaseController
	def message_recieve
		# クライアントからのメッセージを取得
		recieve_message = session[:username] + " : " + message()

		@chatlog = Chatlog.new
		@chatlog.user_id = session[:id]
		@chatlog.text = message()
		@chatlog.room_num = session[:room_id]
		unless @chatlog.save
			render text: 'しっぱい'
		end

		#websocket_chatイベントで接続しているクライアントにブロードキャスト
		#broadcast_message(:websocket_chat, recieve_message)
		webchannel = "websocket_chat_channel_" + session[:room_id]
		WebsocketRails[webchannel].trigger "websocket_chat", recieve_message
	end

	def paint_session_event
		webpaintchannel = "websocket_paint_channel_" + session[:room_id]
		WebsocketRails[webpaintchannel].trigger "websocket_paint_mouse", message()
	end

	def gamestart_event
		p 'gamestart'
		p session[:room_id]
		p session[:id]
		@roommembers = Roomstate.where(['room_num = ?', session[:room_id]])

		@roommembers.each do |roommember|
			p 'aaaaaaa'
			web_my_channel = "web_my_channel_" + session[:room_id].to_s + '_' + roommember.user_id.to_s
			p web_my_channel
			WebsocketRails[web_my_channel].trigger "gamestart", message
		end
	end

	def user_connected
		user_name = session[:username].to_s
		user_state = [message(), user_name]
		p session[:connection_id]

		if message() == 0
			Roomstate.where(['room_num = ? and username = ?', session[:room_id], session[:username]]).limit(1).destroy_all
		else
			@roomstate = Roomstate.new
			@roomstate.room_num = session[:room_id]
			@roomstate.username = session[:username]
			@roomstate.user_id = session[:id]
			@roomstate.connection_id = session[:connection_id]
			@roomstate.save
		end

		@roomstates = Roomstate.where(['room_num = ?', session[:room_id]])
		user_all = '部屋にいるユーザー一覧'
		@roomstates.each do |roomstates|
			user_all = user_all + "<br>" + roomstates.username
		end
		user_state[2] = user_all

		webuserchannel = "websocket_user_channel_" + session[:room_id]
		WebsocketRails[webuserchannel].trigger "websocket_user_channel",user_state
		p user_state
	end

	def client_connected
		p 'abfffffffffffffffffffff'
		session[:connection_id] = message()
	end 

	def client_disconnected
		p 'a55555555555555555555555'
		Roomstate.where(['connection_id = ?', session[:connection_id]]).destroy_all
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tailchats_helper.rb
module TailchatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat/_chat_js.html.erb
<%= javascript_tag do %>
    window.j_web_channel = '<%= j webchannel %>';
    window.j_web_user_channel = '<%= j @webuserchannel %>';
<% end %>

<script>
  //var ws_rails = new WebSocketRails("ws://192.168.33.10:3000//websocket");
  var websocket_chat_channel = ws_rails.subscribe(j_web_channel);
  var websocket_user_channel = ws_rails.subscribe(j_web_user_channel);

  // ページ読み込み時に実行したい処理
  window.onload = function(){
    // 現在の縦スクロール位置
    var scrollPosition = document.getElementById("chat_area").scrollTop;
    // スクロール要素の高さ
    var scrollHeight = document.getElementById("chat_area").scrollHeight;
    document.getElementById("chat_area").scrollTop = scrollHeight;
    //残り文字数を表示
    document.getElementById('characnt').value = 50;
  }

  // メッセージ受信時の処理
  //ws_rails.bind("websocket_chat", function(message){
  websocket_chat_channel.bind("websocket_chat", function(message){
    var message_li = document.createElement("li");
    message_li.textContent = message;
    document.getElementById("chat_area").appendChild(message_li);

    // 現在の縦スクロール位置
    var scrollPosition = document.getElementById("chat_area").scrollTop;
    // スクロール要素の高さ
    var scrollHeight = document.getElementById("chat_area").scrollHeight;
    document.getElementById("chat_area").scrollTop = scrollHeight;
  })

  // メッセージ送信時の処理
  document.getElementById("send").onclick =  function(){
    transmission()
　　}

  function transmission(){
    if (document.getElementById("comment").value != ""){
      var comment = document.getElementById("comment").value;
      ws_rails.trigger("websocket_chat", comment);
      //websocket_chat_channel.trigger("websocket_chat", comment);
      document.getElementById("comment").value = "";
    }
  }
</script>

app/views/chat/_paint_js.html.erb
<%= javascript_tag do %>
    window.j_web_paint_channel = '<%= j webpaintchannel %>';
    window.j_web_my_channel = '<%= j webmychannel %>';
<% end %>

<script>
    var ws_rails = new WebSocketRails("ws://192.168.33.10:3000//websocket");
    var websocket_paint_channel = ws_rails.subscribe(j_web_paint_channel);
    var web_my_channel = ws_rails.subscribe(j_web_my_channel);

    $(function() {
        var canvas = document.getElementById('mycanvas');
        if (!canvas || !canvas.getContext) return false;

        var ctx = canvas.getContext('2d');

        var startX,
            startY,
            x,
            y,
            tranX,
            tranY,
            borderWidth = 20,
            isDrawing = false;

        $('#mycanvas').mousedown(function(e) {
            isDrawing = true;
            startX = e.pageX - $(this).offset().left - borderWidth;
            startY = e.pageY - $(this).offset().top - borderWidth;

            var msg = [ "mousedown", startX, startY, 0, 0 ];
            ws_rails.trigger("websocket_paint_event", msg);
        })
        .mousemove(function(e) {
            if (!isDrawing) return;
            x = e.pageX - $(this).offset().left - borderWidth;
            y = e.pageY - $(this).offset().top - borderWidth;
            ctx.beginPath();
            ctx.lineJoin = "round";
            ctx.lineCap = "round";
            ctx.moveTo(startX, startY);
            ctx.lineTo(x, y);
            ctx.stroke();
            tranX = startX;
            tranY = startY;
            startX = x;
            startY = y;

            var msg = [ "mousemove", tranX, tranY, x, y ];
            ws_rails.trigger("websocket_paint_event", msg);
        })
        .mouseup(function(e) {
            isDrawing = false;
            x = e.pageX - $(this).offset().left - borderWidth;
            y = e.pageY - $(this).offset().top - borderWidth;
            ctx.beginPath();
            ctx.arc(x, y, ctx.lineWidth / 2, 0, Math.PI / 180, true);
            ctx.fill();
            startX = x;
            startY = y;

            var msg = [ "mouseup", x, y, 0, 0 ];
            ws_rails.trigger("websocket_paint_event", msg);
        })
        .mouseleave(function() {
            isDrawing = false;
        });

        $("#penWidth").change(function() {
            ctx.lineWidth = $(this).val();

            var msg = [ "penWidth", ctx.lineWidth, 0, 0, 0 ];
            ws_rails.trigger("websocket_paint_event", msg);
        });
       
        $('li').click(function() {
            ctx.strokeStyle = $(this).css('background-color');
            ctx.fillStyle = $(this).css('background-color');

            var msg = [ "pencoler", ctx.strokeStyle, ctx.fillStyle, 0, 0 ];
            ws_rails.trigger("websocket_paint_event", msg);
        });

        $("#erase").click(function() {
            ctx.clearRect(0, 0, canvas.width, canvas.height);

            var msg = [ "erase", 0, 0, 0, 0 ];
            ws_rails.trigger("websocket_paint_event", msg);
        });

        $("#gamestart").click(function() {
            var msg = [ "gamestart", 0, 0, 0, 0 ];
            ws_rails.trigger("websocket_gamestart_event", msg);
        });

    });

    var saveline,
        relineW;

    websocket_paint_channel.bind("websocket_paint_mouse", function(message){
        var canvas = document.getElementById('mycanvas');
        if (!canvas || !canvas.getContext) return false;
        var ctx = canvas.getContext('2d');

        if (message[0] == "mousedown"){
            //なし
        } else if (message[0] == "mousemove"){
            saveline = ctx.lineWidth;
            ctx.lineWidth = relineW;
            ctx.beginPath();
            ctx.lineJoin = "round";
            ctx.lineCap = "round";
            ctx.moveTo(message[1], message[2]);
            ctx.lineTo(message[3], message[4]);
            ctx.stroke();
            ctx.lineWidth = saveline;
        } else if (message[0] == "mouseup"){
            ctx.beginPath();
            ctx.arc(message[1], message[2], ctx.lineWidth / 2, 0, Math.PI / 180, true);
            ctx.fill();
        } else if (message[0] == "erase"){
            ctx.clearRect(0, 0, canvas.width, canvas.height);
        } else if (message[0] == "penWidth"){
            relineW = message[1];
        } else if (message[0] == "pencoler"){
            ctx.strokeStyle = message[1];
            ctx.fillStyle = message[2];
        }
    })
    
    web_my_channel.bind("gamestart", function(message){
        alert("aaaa");
    })
</script>

app/views/chat/index.html.erb
<% unless current_user.nil? %>
  <% session[:id] = current_user.id %>
  <% session[:username] = current_user.username %>
<% else %>
  <% session[:id] = nil %>
  <% session[:username] = "名無し" %>
<% end -%>
<br>
<% room_num = 1 %>
<% @paintroom.each do |paintroom| %>
  <%= link_to "部屋" + room_num.to_s, chat_path(paintroom), class: :room_name %><br><br>
  <% room_num = room_num + 1 %>
<% end -%>

<ul id="user_area">
	
</ul>

app/views/chat/show.html.erb
<% unless current_user.nil? %>
  <% session[:id] = current_user.id %>
  <% session[:username] = current_user.username %>
<% else %>
  <% session[:id] = nil %>
  <% session[:username] = "名無し" %>
<% end -%>

<div id="penconfig">
  <select id="penWidth">
    <option value="1">細</option>
    <option value="3">中</option>
    <option value="5">太</option>
  </select>

  <ul id="ulColer">
    <li class="selectColer" style="background-color:#000"></li>
    <li class="selectColer" style="background-color:#f00"></li>
    <li class="selectColer" style="background-color:#0f0"></li><br>
    <li class="selectColer" style="background-color:#00f"></li>
    <li class="selectColer" style="background-color:#5C3800"></li>
    <li class="selectColer" style="background-color:#ff0"></li><br>
    <li class="selectColer" style="background-color:#FF00D8"></li>
    <li class="selectColer" style="background-color:#ffffff"></li>
  </ul>

  <input type="button" id="erase" value="消去">

  <p id="user_list">1</p>
</div>

<input type="button" id="gamestart" value="すたーと">

<canvas id="mycanvas" width="600" height="400">Canvasに対応したブラウザを使用してください。</canvas>

<%= render 'paint_js', webpaintchannel: @webpaintchannel, webmychannel: @webmychannel %>

<ul id="chat_area">
  <% unless @chatlogs.nil? %>
    <% @chatlogs.each do |chatlog| %>
      <li><% unless chatlog.user.nil? %>
            <%= chatlog.user.username %> : <%= chatlog.text %>
          <% else %>
            名無し : <%= chatlog.text %>
          <% end -%>
      </li>
    <% end -%>
  <% end -%>
</ul>

<input id="comment" type="text" onkeydown="if(event.keyCode == 13){javascript:transmission();}" onkeyup="document.getElementById('characnt').value=50 - this.value.length" maxlength='50'>
<input id="send" type="button" value="send"><br>
<input type="text" id="characnt" disabled="disabled">
<%= render 'chat_js', webchannel: @webchannel, webuserchannel: @webuserchannel%>

<% unless @roomstates.nil? %>
  <% @roomstates.each do |roomstate| %>
    <%= roomstate.username %><br>
  <% end -%>
<% end -%>

<script>
  window.onload = function(){
    ws_rails.trigger("websocket_online", 1);
  }

  window.onbeforeunload = function(event){
    ws_rails.trigger("websocket_online", 0);
    //event = event || window.event; 
    //event.returnValue = 'ページから移動しますか？';
  }

  //他ユーザー情報受信時
  websocket_user_channel.bind("websocket_user_channel", function(message){
    //alert(message[0]);
    var message_li = document.createElement("li");
    if (message[0] == 0){
      message_li.textContent = message[1] + "が退室しました。";
      document.getElementById("chat_area").appendChild(message_li);
      document.getElementById('user_list').innerHTML=message[2];
    }else{
      message_li.textContent = message[1] + "が入室しました。";
      document.getElementById("chat_area").appendChild(message_li);
      document.getElementById('user_list').innerHTML=message[2];
    }

    // 現在の縦スクロール位置
    var scrollPosition = document.getElementById("chat_area").scrollTop;
    // スクロール要素の高さ
    var scrollHeight = document.getElementById("chat_area").scrollHeight;
    document.getElementById("chat_area").scrollTop = scrollHeight;
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tailchat</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="content">

<% flash.each do |name, msg| %>  
	<%= content_tag :div, msg, :id => "flash#{name}" %>  
<% end %>  

<div id="user_nav">  
  <% if current_user %>  
    ログイン中... <strong><%= current_user.username %></strong>
    <%= link_to "ユーザー情報", edit_user_path(current_user) %> 
    <%= link_to "ログアウト", log_out_path %>  
  <% else %>  
    <%= link_to "ユーザー登録", sign_up_path %> or   
    <%= link_to "ログイン", log_in_path %>  
  <% end %>  
</div> 

<%= yield %>

</div>
</body>
</html>

app/views/users/edit.html.erb
<h1>edit</h1>  

<%= form_for @user do |f| %>  
  <% if @user.errors.any?%>  
    <div class="error_messages">  
      <h2>Form is invalid</h2>  
      <ul>  
        <% for message in @user.errors.full_messages %>  
          <li><%= message %></li>  
        <% end %>
      </ul>
    </div> 
  <% end %>  
  <p>  
    <%= f.label :username %><br />  
    <%= f.text_field :username %>  
  </p> 
  <p>  
    <%= f.label :email %><br />  
    <%= f.text_field :email %>  
  </p>
  <p class="button"><%= f.submit %></p>  
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>  
  
<%= form_for @user do |f| %>  
  <% if @user.errors.any?%>  
    <div class="error_messages">  
      <h2>Form is invalid</h2>  
      <ul>  
        <% for message in @user.errors.full_messages %>  
          <li><%= message %></li>  
        <% end %>  
      </ul>  
    </div>  
  <% end %> 
  <p>  
    <%= f.label :username %><br />  
    <%= f.text_field :username %>  
  </p>  
  <p>  
    <%= f.label :email %><br />  
    <%= f.text_field :email %>  
  </p>  
  <p>  
    <%= f.label :password %><br />  
    <%= f.password_field :password %>  
  </p>  
  <p>  
    <%= f.label :password_confirmation %>  
    <%= f.password_field :password_confirmation %>  
  </p>  
  <p class="button"><%= f.submit %></p>  
<% end %>  